{{ $dot := . }}
{{ range .Values.nodes }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .name }}
  namespace: {{ $dot.Namespace }}
  labels:
    app: ocp-node
    {{- include "bmh-vm.labels" $dot | nindent 4 }}    
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: coreos
        vm.kubevirt.io/workload: ocp-node
      creationTimestamp: null
      labels:
        kubevirt.io/domain: {{ .name }}
        network.kubevirt.io/headlessService: headless
        app: ocp-node
    spec:
      evictionStrategy: LiveMigrate
      architecture: amd64
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
          interfaces:
          {{ if eq $dot.Values.networkConfiguration "simple" }}
            - name: m
              binding:
                name: l2bridge
            - name: vm
              binding:
                name: l2bridge
            - name: st
              binding:
                name: l2bridge                                           
          {{ else if eq $dot.Values.networkConfiguration "bonds" }}
            - name: cp1
              binding:
                name: l2bridge 
            - name: cp2
              binding:
                name: l2bridge
            - name: vm1
              binding:
                name: l2bridge
            - name: vm2
              binding:
                name: l2bridge
            - name: st1
              binding:
                name: l2bridge
            - name: st2
              binding:
                name: l2bridge
          {{ end }}                                                                                    
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        memory:
          guest: 32Gi
        resources: {}
      networks:
        {{ if eq $dot.Values.networkConfiguration "simple" }}
        - name: m
          multus: 
            networkName: m
        - name: vm
          multus: 
            networkName: vm
        - name: st
          multus: 
            networkName: st
        {{ else if eq $dot.Values.networkConfiguration "bonds" }}                
        - name: cp1
          multus: 
            networkName: cp-{{ .name }}-1
        - name: cp2
          multus: 
            networkName: cp-{{ .name }}-2
        - name: vm1
          multus: 
            networkName: vm-{{ .name }}-1
        - name: vm2
          multus: 
            networkName: vm2-{{ .name }}-2
        - name: st1
          multus: 
            networkName: st1
        - name: st2
          multus: 
            networkName: st-{{ .name }}-2
        {{ end }}                               
      terminationGracePeriodSeconds: 180     
      volumes:
        - persistentVolumeClaim:
            claimName: {{ .name }}
          name: rootdisk
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .name }}-bmc"
  namespace: {{ $dot.Namespace }}
  labels: 
    {{- include "bmh-vm.labels" $dot | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    kubevirt.io/domain: {{ .name }}
  ports:
    - name: redfish
      protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $dot.Namespace }}
  labels:
    app: ocp-node
    {{- include "bmh-vm.labels" $dot | nindent 4 }}    
spec:
  storageClassName: {{ $dot.Values.storageClassName }}
  accessModes:  
    - ReadWriteMany 
  resources:
    requests:
      storage: 200Gi 
  volumeMode: Block 
{{ end }}      
