apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: router
  namespace: {{ .Release.Namespace }}
  labels:
    app: router
    {{- include "bmh-vm.labels" . | nindent 4 }}
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: router
      spec:
        source:
          pvc:
            name: vjunos
            namespace: openshift-virtualization-os-images
        # sourceRef:
        #   kind: PersistentVolumeClaim
        #   name: vjunos
        #   namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 50Gi
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
        vm.redhat-cop.dns-name/nic-sapphire-roadrunner-92: fedora-vm1.lab.example.com
      creationTimestamp: null
      labels:
        app: router
        kubevirt.io/domain: fedora-vm1
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
        vm.redhat-cop.dns-name: "true"
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
          features:
          - name: svm
            policy: require             
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
            - name: nm
              binding:
                name: l2bridge
            - name: cp1
              binding:
                name: l2bridge
            - name: cp2
              binding:
                name: l2bridge                
            - name: vm1
              binding:
                name: l2bridge
            - name: vm2
              binding:
                name: l2bridge                                                
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true         
        firmware:
          bootloader:
            bios: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 6Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: nm
          name: nm
        - multus:
            networkName: cp1
          name: cp1
        - multus:
            networkName: cp2
          name: cp2
        - multus:
            networkName: vm1
          name: vm1
        - multus:
            networkName: vm2
          name: vm2                                        
      terminationGracePeriodSeconds: 180
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: {{ .Values.sshPublicKeySecretName }}
          propagationMethod:
            noCloud: {}      
      volumes:
        - dataVolume:
            name: router
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: {{ .Values.password }}
              chpasswd: { expire: False }
            networkData: |-
              version: 2   
              ethernets:
                nm:
                  match:
                    name: enp2s0
                  addresses: [ "192.168.3.1/24" ] 
                  set-name: nm                              
          name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: router-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    app: router
    {{- include "bmh-vm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: router
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22