---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
data:
  haproxy.cfg: |
    global
      log stdout local0
      maxconn 4096
      daemon

    defaults
      log global
      mode tcp
      timeout connect 5000
      timeout client 50000
      timeout server 50000


    frontend fe_ssh
      bind *:2222 ssl crt /etc/haproxy/certs/ssl.pem
      mode tcp
      log-format "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq dst:%[var(sess.dst)] "
      tcp-request content set-var(sess.dst) ssl_fc_sni
      default_backend ssh-all


    backend ssh-all
      mode tcp
      tcp-request content do-resolve(sess.dstIP,default,ipv4) str(sess.dst) ".{{ .Release.Namespace }}.svc"
      tcp-request content set-dst sess.dstIP
      server ssh 0.0.0.0:22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-proxy
  template:
    metadata:
      labels:
        app: ssh-proxy
    spec:
      containers:
      - name: haproxy
        image: registry.connect.redhat.com/haproxytech/haproxy:latest
        ports:
        - containerPort: 2222
          name: ssh-proxy
        volumeMounts:
        - name: config
          mountPath: /etc/haproxy
      volumes:
      - name: config
        configMap:
          name: ssh-proxy

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
spec:
  selector:
    app: ssh-proxy
  ports:
  - port: 2222
    targetPort: 2222
    protocol: TCP
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
spec:
  host: 'ssh-proxy-{{ .Release.Namespace }}.apps.etl6.ocp.rht-labs.com'
  to:
    kind: Service
    name: ssh-proxy
  port:
    targetPort: 2222
  wildcardPolicy: Subdomain
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect  