---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
data:
  haproxy.cfg: |
    global
      log stdout local0
      maxconn 4096
      daemon

    defaults
      log global
      mode tcp
      timeout connect 5000
      timeout client 50000
      timeout server 50000


    frontend fe_ssh
      bind *:2222 ssl crt /etc/haproxy/certs
      mode tcp
      log-format "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq dst:%[var(sess.dst)] "
      tcp-request content set-var(sess.dst) ssl_fc_sni
      default_backend ssh-all


    backend ssh-all
      mode tcp
      tcp-request content set-var(sess.full_host) var(sess.dst_name),concat(".{{ .Release.Namespace }}.svc")
      tcp-request content do-resolve(sess.dst_ip,default,ipv4) var(sess.full_host)
      tcp-request content set-dst var(sess.dst_ip)
      server ssh 0.0.0.0:22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-proxy
  template:
    metadata:
      labels:
        app: ssh-proxy
    spec:
      serviceAccountName: ssh-proxy
      containers:
      - name: haproxy
        image: docker.io/haproxy:lts
        ports:
        - containerPort: 2222
          name: ssh-proxy
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy
        - name: ssh-proxy-tls
          mountPath: /etc/haproxy/certs
      volumes:
      - name: config
        configMap:
          name: ssh-proxy
      - name: ssh-proxy-tls
        secret:
          secretName: ssh-proxy-tls
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.crt.key
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}
  annotations :
    service.beta.openshift.io/serving-cert-secret-name: ssh-proxy-tls
spec:
  selector:
    app: ssh-proxy
  ports:
  - port: 2222
    targetPort: 2222
    protocol: TCP
  type: ClusterIP

---
{{- if true }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-vm.labels" . | nindent 4 }}  
spec:
  host: 'a.ssh-proxy.apps.etl6.ocp.rht-labs.com'
  to:
    kind: Service
    name: ssh-proxy
  port:
    targetPort: 2222
  wildcardPolicy: Subdomain
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: ssh-proxy
    {{- include "bmh-vm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-proxy-anyuid
  namespace: {{ .Release.Namespace }}
  labels:
    app: ssh-proxy
    {{- include "bmh-vm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: ssh-proxy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io      