apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: storage
  namespace: {{ .Release.Namespace }}
  labels:
    app: storage
    {{- include "bmh-vm.labels" . | nindent 4 }}
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: storage
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
        vm.redhat-cop.dns-name/nic-sapphire-roadrunner-92: fedora-vm1.lab.example.com
      creationTimestamp: null
      labels:
        app: storage
        kubevirt.io/domain: fedora-vm1
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
        vm.redhat-cop.dns-name: "true"
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
            {{- if eq .Values.networkConfiguration "simple" }}
            - name: st
              binding:
                name: l2bridge
            {{- else if eq .Values.networkConfiguration "bonds" }}                  
            - name: st1
              binding:
                name: l2bridge
            - name: st2
              binding:
                name: l2bridge
            {{- end }}                
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        {{- if eq .Values.networkConfiguration "simple" }}
        - multus:
            networkName: st
          name: st
        {{- else if eq .Values.networkConfiguration "bonds" }}           
        - multus:
            networkName: st1
          name: st1
        - multus:
            networkName: st2
          name: st2
        {{- end }}           
      terminationGracePeriodSeconds: 180
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: {{ .Values.sshPublicKeySecretName }}
          propagationMethod:
            noCloud: {}      
      volumes:
        - dataVolume:
            name: storage
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: {{ .Values.password }}
              chpasswd: { expire: False }

              # see also https://www.server-world.info/en/note?os=Fedora_40&p=iscsi&f=2                                              
              packages:
              - scsi-target-utils
              write_files:
              - content: | 
                  <target iqn.2024-04.world.srv:dlp.target01>
                      # provided device as a iSCSI target
                      backing-store /var/lib/iscsi_disks/disk01.img
                      # iSCSI Initiator's IQN you allow to connect
                      initiator-name iqn.2024-04.world.srv:node01.initiator
                      # authentication info ( set anyone you like for "username", "password" )
                      incominguser fedora {{ .Values.password }}
                  </target>
                  <target iqn.2024-04.world.srv:dlp.target01>
                      # provided device as a iSCSI target
                      backing-store /var/lib/iscsi_disks/disk02.img
                      # iSCSI Initiator's IQN you allow to connect
                      initiator-name iqn.2024-04.world.srv:node01.initiator
                      # authentication info ( set anyone you like for "username", "password" )
                      incominguser fedora {{ .Values.password }}
                  </target>                                 
                owner: root:root
                path: /etc/sysconfig/selinux
                permissions: '0644'              
              runcmd:
              - mkdir /var/lib/iscsi_disks
              - dd if=/dev/zero of=/var/lib/iscsi_disks/disk01.img count=0 bs=1 seek=10G
              - dd if=/dev/zero of=/var/lib/iscsi_disks/disk02.img count=0 bs=1 seek=10G
              - [ systemctl, daemon-reload ]
              - [ systemctl, enable, tgtd.service ]
              - [ systemctl, start, --no-block, tgtd.service ]
            networkData: |-              
              version: 2
              ethernets:
              {{- if eq .Values.networkConfiguration "simple" }}
                enp2s0:
                  addresses: [ "192.168.1.2/24" ]
                  routes:
                    - to: 192.168.0.0/24 
                      via: 192.168.1.1
                    - to: 192.168.3.0/24 
                      via: 192.168.1.1                  
              {{- else if eq .Values.networkConfiguration "bonds" }}                  
                enp2s0:
                  addresses: [ "192.168.1.2/24" ]
                enp3s0:
                  addresses: [ "192.168.2.2/24" ]
              {{- end }}                                      
          name: cloudinitdisk
---
apiVersion: v1
kind: Service
metadata:
  name: storage-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    app: storage
    {{- include "bmh-vm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22    

